# Generated by Django 2.1.4 on 2019-10-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enamour', '0011_auto_20191004_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('firstname', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('txnid', models.CharField(max_length=20)),
                ('productinfo', models.CharField(max_length=20)),
            ],
        ),
    ]
