# Generated by Django 2.1.4 on 2019-10-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0017_expendtituredetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('amoount_paid', models.FloatField()),
                ('date_enrolled', models.DateField()),
            ],
        ),
    ]
